# Dependabot will run on day 12 of each month at 03:58 (Europe/Berlin timezone)
version: 2
updates:
  - package-ecosystem: "npm"
    schedule:
      interval: "cron"
      timezone: "Europe/Berlin"
      cronjob: "58 3 12 * *"
    open-pull-requests-limit: 15
    assignees:
      - "FernetMenta"
    versioning-strategy: "increase"
    directories: "**/*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "cron"
      timezone: "Europe/Berlin"
      cronjob: "58 3 12 * *"
    open-pull-requests-limit: 15
    assignees:
      - "FernetMenta"
